### ISSUE TITLE
setInput callback doesn't pass data parameter on success

### ISSUE THREAD

**Issue by ascl00** [k3erg/marantz-denon-telnet#4]
```
MarantzDenonTelnet.prototype.setInput = function(input, callback, zone) {
    var commandPrefix = (!zone || (zone == 'ZM')) ? 'SI' : zone;

    this.telnet(commandPrefix + input, function(error, data) {
        if (!error) {
            callback(null);
        } else {
            callback(error);
        }
    });
};
```

Every other callback passes data back on success, so this method should be defined as:
```
MarantzDenonTelnet.prototype.setInput = function(input, callback, zone) {
    var commandPrefix = (!zone || (zone == 'ZM')) ? 'SI' : zone;

    this.telnet(commandPrefix + input, function(error, data) {
        if (!error) {
            callback(null, data);
        } else {
            callback(error);
        }
    });
};
```

**Comment by k3erg** [comment]
@ascl00 This is by design.

To my understanding of the protocol specs and my tests:

A `COMMAND` only triggers a direct `RESPONSE` within 200ms, if it was a `request command`.
Every `COMMAND` can lead to a state change of the AVR, in which case the AVR emits an `EVENT`. The `EVENT` is in structure the same as a `RESPONSE`. But the `EVENT` is unsolicited, i.e. it can occur at any time and we can't rely on it. For example the `PWON` `COMMAND` can take up to 3 sec and will then send an `EVENT`.

My chosen design is a compromise of having a simple structure by relying upon a `RESPONSE` wthin 200ms and dropping `EVENT`s. It is a known issue, that an `EVENT` can occur between an `COMMAND` and a `RESPONSE` disruppting the design.

The 'proper' design would be to have a completely separated output-cue and input-cue and then try to match them by inspecting the `EVENT` –  I took a stab at it, but it was turning out a bit of a too big project for the simple use I had in mind. But I'm not opposed to it :) .

**Comment by ascl00** [comment]
Maybe you misunderstood me. If you look at setMuteState for eg,  you will see that the callback on success passes back the data. In fact, every "set" except for setInput() has this behaviour.

I am not suggesting a major change (at all), this works the majority of the time. Just a simple change to make setInput consistent with all the other "set" methods.

**Comment by k3erg** [comment]
Ah, sorry, now I see, txs!
It's in.

Never the less was good to have to sum up the (current) concept and pitfalls of the lib in a post. :)

**Comment by ascl00** [comment]
Ugh. I just read through the spec, and see there is no way to distinguish between a response and an event...  and see what you were talking about. That's ugly. Although, one of the reasons I used this library is that it doesn't hold a persistent connection open. AFAIK the AVR only accepts a single connection, so one persistent connection blocks everyone else...

Thanks for getting these changes in.

**Comment by k3erg** [comment]
Exactly, one connection only, hence this approach.
